apiVersion: v1
kind: Pod
metadata:
  name: nginx-privileged
  namespace: default
  labels:
    allowPrivilegeEscalation: "yes"
spec:
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
        allowPrivilegeEscalation: true
    - name: sleeping-sidecar
      image: alpine
      command: ["sleep", "1h"]
