repositories:
  - name: jaegertracing
    url: https://jaegertracing.github.io/helm-charts

helmDefaults:
  createNamespace: true
  timeout: 180 
  atomic: true
  verify: false
  wait: true

releases:
  - name: jaeger-operator
    namespace: jaeger
    version: 2.49.0
    chart: jaegertracing/jaeger-operator
    values:
      - rbac:
          clusterRole: true
  - name: jaeger-kubewarden
    chart: ../charts/jaeger
    namespace: jaeger
    disableValidationOnInstall: true
    needs:
      - jaeger-operator
