
name: updatecli
on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run every hour
    - cron: '0 * * * *'
jobs:
  updatecli:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Setup updatecli"
        uses: "updatecli/updatecli-action@v2"

      - name: "Run updatecli in dryrun"
        run: "updatecli diff --config ./updatecli/updatecli.d  --experimental"
        env:
          UPDATECLI_GITHUB_ACTOR: ${{ github.actor }}
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Run updatecli"
        if: github.ref == 'refs/heads/main'
        run: "updatecli apply --config ./updatecli/updatecli.d --experimental" 
        env:
          UPDATECLI_GITHUB_ACTOR: ${{ github.actor }}
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
